WATCHLIST_SEED = [
    {
        "slug": "aave-v3",
        "display_name": "Aave V3",
        "category": "lending",
        "tier": "special",
        "pinned": True,
        "metrics": ["tvl", "supply", "borrowed", "utilization"],
    },
    {
        "slug": "cian-yield-layer",
        "display_name": "CIAN Yield Layer",
        "category": "yield",
        "tier": "generic",
        "pinned": False,
        "metrics": ["tvl"],
    },
    {
        "slug": "mantle-index-four-fund",
        "display_name": "Mantle Index Four Fund (MI4)",
        "category": "index",
        "tier": "generic",
        "pinned": False,
        "metrics": ["tvl"],
    },
    {
        "slug": "merchant-moe",
        "display_name": "Merchant Moe",
        "category": "dex",
        "tier": "dex",
        "pinned": False,
        "metrics": ["tvl", "volume"],
    },
    {
        "slug": "treehouse-protocol",
        "display_name": "Treehouse Protocol",
        "category": "yield",
        "tier": "generic",
        "pinned": False,
        "metrics": ["tvl"],
    },
    {
        "slug": "ondo-yield-assets",
        "display_name": "Ondo Yield Assets",
        "category": "rwa",
        "tier": "generic",
        "pinned": False,
        "metrics": ["tvl"],
    },
    {
        "slug": "agni-finance",
        "display_name": "Agni Finance",
        "category": "dex",
        "tier": "dex",
        "pinned": False,
        "metrics": ["tvl", "volume"],
    },
    {
        "slug": "stargate-finance",
        "display_name": "Stargate Finance",
        "category": "bridge",
        "tier": "generic",
        "pinned": False,
        "metrics": ["tvl"],
    },
    {
        "slug": "apex-omni",
        "display_name": "ApeX Protocol",
        "category": "derivatives",
        "tier": "generic",
        "pinned": False,
        "metrics": ["tvl"],
    },
    {
        "slug": "compound-v3",
        "display_name": "Compound V3",
        "category": "lending",
        "tier": "generic",
        "pinned": False,
        "metrics": ["tvl"],
    },
    {
        "slug": "uniswap-v3",
        "display_name": "Uniswap V3",
        "category": "dex",
        "tier": "dex",
        "pinned": False,
        "metrics": ["tvl", "volume"],
    },
    {
        "slug": "init-capital",
        "display_name": "INIT Capital",
        "category": "lending",
        "tier": "generic",
        "pinned": False,
        "metrics": ["tvl"],
    },
    {
        "slug": "woofi",
        "display_name": "WOOFi",
        "category": "dex",
        "tier": "dex",
        "pinned": False,
        "metrics": ["tvl", "volume"],
    },
    {
        "slug": "fluxion-network",
        "display_name": "Fluxion Network",
        "category": "dex",
        "tier": "dex",
        "pinned": False,
        "metrics": ["tvl", "volume"],
    },
]
